---

- name: Configure a linuxmuster.net client
  hosts: [ 'ypid_service_linuxmuster_net_client' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.linuxmuster_net_client
      tags: [ 'role::linuxmuster_net_client' ]
